### ISSUE TITLE
Library evaluation tracking issue

### ISSUE THREAD

**Issue by brson** [BurntSushi/byteorder#76]
- [x] Add a supertrait to hide trait details https://github.com/BurntSushi/byteorder/issues/69
- [x] ByteOrder::default should panic! not unreachable! https://github.com/BurntSushi/byteorder/issues/68
- [x] Put panic and error docs in "Panics" and "Errors" sections https://github.com/BurntSushi/byteorder/issues/72
- [x] Make sure there are enough examples https://github.com/BurntSushi/byteorder/issues/75
- [x] Add CI badges to Cargo.toml https://github.com/BurntSushi/byteorder/issues/74
- [x] Add "categories" to Cargo.toml https://github.com/BurntSushi/byteorder/issues/73
- [x] Add #[doc(html_root)] https://github.com/BurntSushi/byteorder/issues/77

This is the tracking issue for the [evaluation](https://gist.github.com/brson/ab5808dedd65256dead709a1fb431ab0) performed by the libs team last week.

**Comment by BurntSushi** [comment]
Done! Thanks to @SamWhited!
